### ISSUE TITLE
MVC Review

### ISSUE THREAD

**Issue by so2niko** [anton-sedchenko/WebUI#4]
- [ ] work with events must be in View
https://github.com/anton-sedchenko/WebUI/blob/f56f2d9fa4cadae28e1c540cbb36578e2fee7e93/HW_8/app/controller.js#L11
___________________________________
- [ ] method in View
https://github.com/anton-sedchenko/WebUI/blob/f56f2d9fa4cadae28e1c540cbb36578e2fee7e93/HW_8/app/model.js#L6-L9
_________________________________

**Comment by anton-sedchenko** [comment]
fixed
